### ISSUE TITLE
jsdelivr down - remove point of failure in settings.json

### ISSUE THREAD

**Issue by actraiser** [opral/inlang-paraglide-js#103]
jsdelivr.net has gone down because of a TLS/SSL-Certificate error making it hard to deploy projects using paraglide-js.  I tried manually installing the modules referenced in settings.json but it failed on a postinstall scripts related to those packages.

Please make it easier to replace the cdn-URLs in the settings with locally installed modules.

```
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "en",
  "languageTags": ["en", "de"],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js"
  ],
  "plugin.inlang.messageFormat": {
    "pathPattern": "./messages/{languageTag}.json"
  }
}
```

Greets
-act

PS: temporary workaround is to use a mirror, e.g https://fastly.jsdelivr.net

**Comment by LorisSigrist** [comment]
This is something we want to address with local module caching. <br><br>See: [https://github.com/opral/inlang-message-sdk/issues/43](https://github.com/opral/inlang-message-sdk/issues/43)<br><br>We can't use a regular package manager like NPM because it needs to be possible to load the modules in the browser for Apps like [Fink](https://inlang.com/m/tdozzpar/app-inlang-finkLocalizationEditor) to work. <br><br>I'll mark this as a duplicate since the linked issue should cover your need.

**Comment by samuelstroschein** [comment]
@jldec this confirms our discussions yesterday. if one (or all) modules fail to load, the project should still work. Requires [message persistency](https://linear.app/opral/project/message-persistency-d9f01eb1f180) first to make this work to get rid of plugin dependencies
