### ISSUE TITLE
Who or what is dxnzrydw ?

### ISSUE THREAD

**Issue by benmccann** [opral/inlang-paraglide-js#179]
Why is the URL for the Paraglide-SvelteKit docs https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n ? I don't understand why dxnzrydw is in the URL. Could we drop it from the URL? It'd be so much nicer without it

**Comment by samuelstroschein** [comment]
that's the id in the [registry](https://github.com/opral/monorepo/blob/main/inlang/source-code/marketplace-registry/registry.json). the ids exists to prevent renames to break existing links. the benefit of non-breaking links outweighs the cost of uglier links imo. 

we could move the id to the end 

```diff
- https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n
+ https://inlang.com/m/paraglide-sveltekit-i18n/dxnzrydw
```

but it seems minor

**Comment by benmccann** [comment]
The main reason it bothers me is that it kind of makes it look like it's owned by a user named `dxnzrydw` given how much I'm used to seeing GitHub repos referred to as `opral/monorepo`, `sveltejs/kit`, `dxnzrydw/paraglide-sveltekit-i18n`, etc. For a first-time user or visitor to the site, it's hard to understand where this ID is coming from and easy to assume it could the GitHub owner or something along those lines. Reversing it would probably mostly solve that issue

It's also better for SEO to avoid unnecessary URL segments - each time you add a segment you page will rank worse. E.g. https://www.outreachmama.com/blog/properly-optimized-url/. Reversing wouldn't help as much there. But I'd bet there are other ways you could avoid broken links such as something that checks that each of those URLs exists (either as a page or redirect) on build or as a separate process run against the deployed site.

**Comment by samuelstroschein** [comment]
Good argument that a user might be irritated that `dxnzrydw` is a publisher. 

Medium uses trailing ids [https://medium.com/@cramforce/designing-even-larger-applications-460ee029012d](https://medium.com/@cramforce/designing-even-larger-applications-460ee029012d) which solves the "who is this weird publisher". 

@nils.jacobsen change to suffix instead of prefix for registry ids? <br>(I would refrain from avoiding the id in the url. we would need to keep an internal redirect map. too complicated.)

**Comment by benmccann** [comment]
Ooh nice. Putting it at the end with a `-` like Medium does seems a lot more appealing to me than using a `/`. It'd be better for SEO and also just seems better conceptually whereas `/` is closer to representing a subdirectory

**Comment by NilsJacobsen** [comment]
Putting the id behind the page title sounds like a interesting proposal. <br><br>Some thoughts:

* When the user name would be used in front, I would think that I can get to a user page too, which is not the case rn?
* Parsing the id out of the title seams not super stable `-` is typically displaying a `space` in the title not a separation.
* Changing this now would be a big SEO rewiring effort, since we don't want to drop the SEO traffic onto existing pages.

I think we can think about that in the future but now the necessity doesn't seam to be big enough to pull this off.

**Comment by samuelstroschein** [comment]
> I think we can think about that in the future but now the necessity doesn't seam to be big enough to pull this off.

👍 

If we create new sites, let's keep in mind that the id at the end would be better. 

> * When the user name would be used in front, I would think that I can get to a user page too, which is not the case rn?

Can be added with `/publisher/id` doesn't have to be the github style `publisherId/productId`.

**Comment by NilsJacobsen** [comment]
Alright 👍 Thanks for sharing ben :)
