### ISSUE TITLE
Confusing message: `Using existing cloned repo`

### ISSUE THREAD

**Issue by benmccann** [opral/inlang-paraglide-js#244]
When you create a brand new SvelteKit project with paraglide it says `Using existing cloned repo`. This is confusing because the project is not in source control

The message looks to be coming from these locations:
```
./node_modules/.pnpm/@lix-js+client@2.2.1/node_modules/@lix-js/client/src/repoState.ts:		console.info("Using existing cloned repo")
./node_modules/.pnpm/@lix-js+client@2.2.1/node_modules/@lix-js/client/dist/repoState.js:        console.info("Using existing cloned repo");
./node_modules/.pnpm/@inlang+paraglide-js@1.11.3/node_modules/@inlang/paraglide-js/dist/cli/index.js:    console.info("Using existing cloned repo");
```

**Comment by samuelstroschein** [comment]
Is fixed in Paraglide JS 2.0. 

That's the old [lix](https://lix.opral.com/) client that has been built on git. The inlang SDK initialized an in memory git repo when no repo exists. The git repo was the persistency layer for the inlang SDK, and thereby, for inlang apps like Paraglide JS, Sherlock, Fink, etc. 

We ripped out git as persistency layer, see "[building on git was our failure mode](https://opral.substack.com/p/building-on-git-was-our-failure-mode)", in favor of SQLite to de-couple external repos from internal state.
