### ISSUE TITLE
SvelteKit Auto-Generated files do not work in deployed environment (`paraglide` directory is `.gitignore`d and the files are not being generated)

### ISSUE THREAD

**Issue by skamansam** [opral/inlang-paraglide-js#260]
I used the sveltekit starter and verified that the same code was there that should be there according to the [documentation](https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/manual-setup). This adds a .gitignore to the `/src/lib/paraglide` directory. This means those files should be generated during the build process, but are not getting built. This causes the deployment to vercel to fail. 

Of note, when I try to build my project with the `paraglide` directory missing, I get the same errors. Shouldn't the `vite build` process make sure these files are generated? My repo is here: https://github.com/skamansam/questlists-svelte

My errors are:
```
error during build:
[vite:load-fallback] Could not load /vercel/path0/src/lib/paraglide/messages.js (imported by src/routes/demo/paraglide/+page.svelte): ENOENT: no such file or directory, open '/vercel/path0/src/lib/paraglide/messages.js'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1238:14)
    at async Object.load (file:///vercel/path0/node_modules/.pnpm/vite@5.4.11_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65091:25)
    at async PluginDriver.hookFirstAndGetPlugin (file:///vercel/path0/node_modules/.pnpm/rollup@4.27.2/node_modules/rollup/dist/es/shared/node-entry.js:21099:28)
    at async file:///vercel/path0/node_modules/.pnpm/rollup@4.27.2/node_modules/rollup/dist/es/shared/node-entry.js:20219:33
    at async Queue.work (file:///vercel/path0/node_modules/.pnpm/rollup@4.27.2/node_modules/rollup/dist/es/shared/node-entry.js:21309:32)
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm build" exited with 1
```

**Comment by samuelstroschein** [comment]
Change `fa_IR` to `fa-IR` and your problem is fixed. 

PS the unreleased v2 of the inlang SDK does not require BCP-47 language tags anymore. Any locale will be possible in the future 

---

`fa_IR` is not a valid BCP-47 language tag. VSCode lints that. 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/8dafafd8-1245-4708-bc2e-7180bdeec1e9/ea20fac5-5ec0-41f3-9f2f-9124abba0137?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC84ZGFmYWZkOC0xMjQ1LTQ3MDgtYmMyZS03MTgwYmRlZWMxZTkvZWEyMGZhYzUtNWVjMC00MWYzLTlmMmYtOTEyNGFiYmEwMTM3IiwiaWF0IjoxNzMyNDkyNTUxLCJleHAiOjMzMzAzMDUyNTUxfQ.8YPdKCBITIAVFfUYU21YmSVVAl3uIRkb0dRPzwSRNlo " alt="CleanShot 2024-11-24 at 18.52.16@2x.png" width="1732" height="734" />

The build subsequently fails with this error message. 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/54a918e4-d87f-4051-8f9b-6245825ea78e/8fbf2381-5e0f-4a22-a927-414155a12ecf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC81NGE5MThlNC1kODdmLTQwNTEtOGY5Yi02MjQ1ODI1ZWE3OGUvOGZiZjIzODEtNWUwZi00YTIyLWE5MjctNDE0MTU1YTEyZWNmIiwiaWF0IjoxNzMyNDkyNTUxLCJleHAiOjMzMzAzMDUyNTUxfQ.S_u9sm3TKJMyZqCnzXWigC8rjWZFjaRieeJBKukkMJQ " alt="CleanShot 2024-11-24 at 18.52.51@2x.png" width="1762" height="440" />

Changing the language tag to `fa-IR` leads to a successful build. 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/b99eb953-eff2-4598-adfe-19010b24c882/29398b9b-bf85-416f-b07f-51583f27a72a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iOTllYjk1My1lZmYyLTQ1OTgtYWRmZS0xOTAxMGIyNGM4ODIvMjkzOThiOWItYmY4NS00MTZmLWIwN2YtNTE1ODNmMjdhNzJhIiwiaWF0IjoxNzMyNDkyNTUxLCJleHAiOjMzMzAzMDUyNTUxfQ.-Uubmbit_znjQSBPF1xUQGItyXU7V_OdwDHrf79gETA " alt="CleanShot 2024-11-24 at 18.54.26@2x.png" width="1044" height="170" />

**Comment by skamansam** [comment]
Thank you very much! I wasn't aware of the BCP-47, but I defintely am now!
