### ISSUE TITLE
Paraglide-Next makes server-actions hang

### ISSUE THREAD

**Issue by herkulano** [opral/inlang-paraglide-js#28]
### Problem

Using `paraglide-js-adapter-next` middleware with Next 14 breaks server actions.

The server action is kept hanging and never returns.

It only breaks on "non-default" languages:
`/pt/signin` doesn't work 
`/signin` works

### Expected behavior

Server action should not hang.

### Reproduction

Use the middleware with a Next 14 server action with a non-default language

**Comment by LorisSigrist** [comment]
I accidentally closed this while removing duplicates in Linear. For some reason this issue was in there twice. Sorry about this

**Comment by LorisSigrist** [comment]
The reason this happens currently is because the adapter doesn't properly call `setLanguageTag()` from the paraglide runtime before server actions get executed. Next doesn't provide a clear place where setup-code for server-actions can be run. Middleware doesn't work because it's in a separate process. 

The only reliable way I can think of is to set the language tag in module-scope before the server-actions module is executed. This would likely require making `runtime.js` frameworks specific. It would almost certainly require API changes. 

A workaround for now is to call `setLangaugeTag` manually before the actions.

```ts
//actions.ts
import { headers } from "next/headers"
import { setLanguageTag, type AvailableLanguageTag } from "@/paraglide/runtime.js"

setLanguageTag(()=>{
   return headers().get("x-language-tag") as AvailableLanguageTag
})
```

This snipped could be placed in it's own module which is then imported into the actions file.


Server-Actions that are declared in the same file as components using `"use server"` inside a function should already work as expected & don't need this workaround

**Comment by LorisSigrist** [comment]
The next version of the adapter will include an `initializeLanguage` function that does the above workaround automatically. 

```
// src/app/actions.ts
"use server";
import { initializeLanguage } from "@inlang/paraglide-next"
import { languageTag } from "@/paraglide/runtime"

initializeLanguage() // call at the top of your file

export function myAction() {
  languageTag() //will return the correct language
}
```

Hopefully we find a way to do this automatically but until then this workaround will need to do

**Comment by LorisSigrist** [comment]
With version 0.1.6 of `@inlang/paraglide-next` server actions now work as expected
