### ISSUE TITLE
SvelteKit - Compiled translations in wrong dir

### ISSUE THREAD

**Issue by UlrichRaab** [opral/inlang-paraglide-js#58]
I have defined a custom outdir in `vite.config.ts` but the compiled translations are not in the defined dir when i run `npm run build`. When i use `npm run dev` everything works as expected.

Here is my `vite.config.ts`:

```typescript
import { paraglide } from '@inlang/paraglide-js-adapter-sveltekit/vite';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
 
export default defineConfig({
 plugins: [
  paraglide({
   project: './project.inlang',
   outdir: './src/gen/paraglide'
  }),
  sveltekit()
 ]
});
```

**Comment by LorisSigrist** [comment]
It's possible that you have a `paraglide-js build` CLI call in your `package.json` build script. Try removing it and re-running. Does the issue persist?

**Comment by LorisSigrist** [comment]
The call is automatically added by `paraglide-js init`. It does this because it can't be assumed that people are using a build tool like vite, so it adds calls to the compiler CLI.

You can safely remove the call from the `build` script. 
The `postinstall` script may be important if you are linting/typechecking in CI without building first, since the paraglide files would be missing. Add `--outdir ./src/gen/paraglide` to the command. 

The newest version of the init CLI will always add the `outdir` flag to the commands to hopefully make it a little more transparent. 

We should document this better
